name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # once per day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: frijae
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
      - name: Upload to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
